# baseURL: "https://ossig.netlify.com/"
disableKinds: ["taxonomy", "taxonomyTerm"]
languageCode: en-us
title: OHBM Open Science SIG
theme: hugo-fresh

params:
  navbarlogo:
    # Logo (from /images/logos/___)
    image: logos/ossig_logo.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400, 600]
  hero:
    # Main hero title
    title: The OHBM Open Science Special Interest Group
    # Hero subtitle (optional)
    subtitle: Dedicated to promoting and supporting open science within our community
    # Button text
    buttontext: Learn more
    # Where the main hero button links to
    buttonlink: "#openumbrella"
    # Hero image (from /images/___)
    image: illustrations/undraw_scrum_board.svg

  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
    - title: Our Team 2023
      url: "/#OSSIG_team"
    - title: Join the OSSIG Committee
      url: "/elections"
    - title: Hackathon
      url: "https://ohbm.github.io/hackathon"
    #- title: Call for fellows
    #  url: "/awards"
    - title: Open Science Room
      url: "https://ohbm.github.io/osr2024"
    - title: Sponsors
      url: "/sponsors"
    - title: Past members
      url: "/pastmembers"
  # - title: Bylaws
  #   url: https://docs.google.com/document/d/1_tfGJMtcwebVM06Z2AzNZ70JT1ID2S48fGCIqJwDyg0/edit?usp=sharing
  # - title: Join the OSSIG
  #   url: https://bit.ly/OHBMOSSIG2021Nominations

  hackathon:
    title: Save the date
    subtitle: It is coming... Finally.
    id: hackathon
    image: illustrations/landing_hackathon_2020.jpg
    buttonText: More info here
    buttonLink: https://github.com/ohbm/hackathon2020/blob/master/README.md

  team:
    title: Our team 2023
    subtitle: The people behind the OSSIG
    id: OSSIG_team
    year: 2023
    # images (from /images/faces/2023/___.jpg)
    members:
      # chair, secretary, treasurer
      - name: Koen Haak
        role: Chair
        image: koen_haak1
        affiliation: Donders Institute for Brain Cognition and Behaviour, Radboud University Medical Center, Nijmegen, The Netherlands
        twitter: https://twitter.com/KVHaak
      - name: Andrea Gondova
        role: Secretary
        image: gondova_andrea1
        affiliation:  Université de Paris Cité, NeuroDiderot INSERM; UNIACT Neurospin CEA; Paris, France
        twitter: https://twitter.com/reaGondova
      - name: Linden Parkes
        role: Treasurer
        image: linden_parkes1
        affiliation: University of Pennsylvania
        twitter: https://twitter.com/LindenParkes

      # hackathon
      - name: Yu-Fang Yang
        role: Hackathon Co-Chair
        image: yufang_yang1
        affiliation: Division of Experimental Psychology and Neuropsychology, Department of Education and Psychology, Freie Universität Berlin
        twitter: https://twitter.com/ufangyang
      - name: Anibal Sólon Heinsfeld
        role: Hackathon Co-Chair
        image: anibal_solon1
        affiliation: Department of Psychology & Department of Computer Science, The University of Texas at Austin, USA
        twitter: https://twitter.com/anibalsolon


      # OSR
      - name: Subapriya Suppiah
        role: Open Science Room Co-Chair
        image: subapriya_suppiah1
        affiliation: Universiti Putra Malaysia
        twitter: https://twitter.com/SubapriyaSuppi1
      - name: Selma Lugtmeijer
        role: Open Science Room Co-Chair
        image: selma_lugtmeijer1
        affiliation: Brock University, Department of Psychology, Canada
        twitter: https://twitter.com/LugtmeijerSelma

      # Hybridization
      - name: Junhao Wen (Hao)
        role: Hybridization Chair
        image: junhao_wen1
        affiliation: University of Southern California
        twitter: https://twitter.com/JunhaoWen

      # inclusivity officer
      - name: Fernando A. Barrios
        role: Inclusivity Officer
        image: fernando_barrios1
        affiliation: Universidad Nacional Autónoma de México, Instituto de Neurobiología, Mexico
        twitter: 
      - name: Kangjoo Lee
        role: Inclusivity Officer
        image: kangjoo_lee1
        affiliation: Yale University, Department of Psychiatry, USA
        twitter: https://twitter.com/Kangjoo_Lee_ 

      # Community Liason Officers
      - name: Nur Shahidatul Nabila binti Ibrahim
        role: Community Liason Officer
        image: nur_nabila1
        affiliation: Universiti Putra Malaysia
        twitter: 
      - name: Almudena Ramírez Haro
        role: Community Liason Officer
        image: almudena_ramirez_haro1
        affiliation: 
        twitter:

      # elect chair, secretary, treasurer
      - name: Nils Muhlert
        role: Chair Elect
        image: nils_muhlert1
        affiliation: University of Manchester
        twitter: https://twitter.com/nilsmuhlert
      - name: Subapriya Suppiah
        role: Secretary Elect
        image: subapriya_suppiah1
        affiliation: Universiti Putra Malaysia
        twitter: https://twitter.com/SubapriyaSuppi1
      - name: Yi-Ju Lee (Jean)
        role: Treasurer Elect
        image: yiju_lee1
        affiliation: Institute of Statistical Science, Academia Sinica, Taipei, Taiwan
        twitter: https://twitter.com/jean890203

      # elect brainhack/OSR
      - name: Qing Wang (Vincent)
        role: Hackathon Co-Chair Elect
        image: qing_wang1
        affiliation: Shanghai Mental Health Center, Shanghai Jiao Tong University Medical School, China
        twitter: https://twitter.com/QingWan99752335
      - name: Sina Mansour
        role: Hackathon Co-Chair Elect
        image: sina_mansour1
        affiliation: Department of Psychiatry, The University of Melbourne
        twitter: 
      - name: Xiangzhen Kong
        role: Open Science Room Co-Chair Elect
        image: xiangzhen_kong1
        affiliation: Department of Psychology and Behavioral Sciences, Zhejiang University
        twitter: https://twitter.com/xiangzhenkong

  sponsors:
    title: Our sponsors
    subtitle: We are grateful for the generous support of our 2023 sponsors.
    titleopp: Sponsorship opportunities
    tiersimage: /images/illustrations/ossig_sponsorpship_tiers2023.jpg
    subtitleopp: Interested in supporting us? Please see our sponsorship opportunities below!
    sponsors:

      - name: Hackathon Champion
        oursponsors:
          - name: "Openneuro"
            image: /images/logos/openneuro_logo.png
            height: 8em
            url: https://openneuro.org/
    
      - name: Hackathon Champion
        oursponsors:
          - name: " Child Mind Institute"
            image: cmi.png
            height: 8em
            url: https://childmind.org/
            
      - name: Hackathon Champion
        oursponsors:
          - name: "TReNDS Center"
            image: /images/logos/trends.svg
            height: 8em
            url: https://trendscenter.org/
            
      #- name: Hackathon Supporters
      #  oursponsors:
      #    - name: "NiPreps"
      #      image: /images/logos/openneuro_logo.png
      #      height: 16em
      #      url: https://openneuro.org/

      - name: Hackathon Champion
        oursponsors:
          - name: "BIDS Connectivity group "
            image: /images/logos/bids.jpg
            height: 8em
            url: https://bids.neuroimaging.io/get_involved

      - name: Hackathon Champion
        oursponsors:
          - name: "NiPreps"
            image: /images/logos/nipreps.jpg
            height: 8em
            url: https://www.nipreps.org/
            
      - name: Hackathon Supporter
        oursponsors:
          - name: "Psychoradiology"
            image: /images/logos/psychoradiology.jpg
            height: 8em
            url: https://academic.oup.com/psyrad

      - name: Hackathon Supporter
        oursponsors:
          - name: "Canadian Open Neuroscience Platform"
            image: /images/logos/conp_logo.png
            height: 8em
            url: ttps://conp.ca/
            
      - name: Open Science Room Supporter
        oursponsors:
          - name: "Wellcome Centre for Integrative Neuroimaging"
            image: /images/logos/logo_WIN_clear.png
            height: 8em
            url: https://www.win.ox.ac.uk/     

      - name: Open Science Room Supporter
        oursponsors:
          - name: "MathWorks"
            image: /images/logos/mathworks_logo.png
            height: 7em
            url: https://www.mathworks.com/


  section2:
    title: Open science is an umbrella.
    subtitle: We're here to help grow the community supporting it.
    id: openumbrella
    features:
      - title: Open data
        text: Sharing neuroimaging data isn't easy, but we can make it easier. We're interested in understanding how OHBM members share data, where they encounter difficulties, and what kinds of new infrastruce and ethics can make next-generation data-sharing possible.
        # Icon (from /images/illustrations/icons/___.svg)
        icon: mouse-globe
      - title: Open code
        text: Analysis code is often a second-class citizen in neuroimaging research, but we can change that. We help to teach scientists best-practices in software development—and how those practices can result in real-world gains in research quality and output.
        icon: laptop-cloud
      - title: Open publishing
        text: Papers shouldn't hide behind paywalls. We want to help create solutions to enable new, open-acess platforms and to facilitate free information.
        icon: doc-sync


  footer:
    # Logo (from /images/logos/___)
    logo: ossig_logo.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
      - link: https://github.com/OHBM
        # Icons are from Font Awesome
        icon: github
      - link: https://twitter.com/ohbmopen
        icon: twitter
    bulmalogo: false
