# baseURL: "https://ossig.netlify.com/"
disableKinds: ["taxonomy", "taxonomyTerm"]
languageCode: en-us
title: OHBM Open Science SIG
theme: hugo-fresh

params:
  navbarlogo:
    # Logo (from /images/logos/___)
    image: logos/ossig_logo.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400, 600]
  hero:
    # Main hero title
    title: The OHBM Open Science Special Interest Group
    # Hero subtitle (optional)
    subtitle: Dedicated to promoting and supporting open science within our community
    # Button text
    buttontext: Learn more
    # Where the main hero button links to
    buttonlink: "#openumbrella"
    # Hero image (from /images/___)
    image: illustrations/undraw_scrum_board.svg

  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
    - title: Our Team
      url: "/#OSSIG_team"
    - title: Join the OSSIG Committee
      url: "/elections"
    - title: Hackathon
      url: "https://ohbm.github.io/hackathon"
    - title: Awards
      url: "/awards"
    - title: Open Science Room
      url: "https://ohbm.github.io/OpenScienceRoom"
    - title: Sponsors
      url: "/sponsors"
    - title: Past members
      url: "/pastmembers"
  # - title: Bylaws
  #   url: https://docs.google.com/document/d/1_tfGJMtcwebVM06Z2AzNZ70JT1ID2S48fGCIqJwDyg0/edit?usp=sharing
  # - title: Join the OSSIG
  #   url: https://bit.ly/OHBMOSSIG2021Nominations

  hackathon:
    title: Save the date
    subtitle: It is coming... Finally.
    id: hackathon
    image: illustrations/landing_hackathon_2020.jpg
    buttonText: More info here
    buttonLink: https://github.com/ohbm/hackathon2020/blob/master/README.md

  team:
    title: Our team
    subtitle: The people behind the OSSIG
    id: OSSIG_team
    year: 2021
    # images (from /images/faces/$year/___.jpg)
    members:
      # chair, secretary, treasurer
      - name: Aki Nikolaidis
        role: Chair
        image: aki_nikolaidis
        affiliation: Child Mind Institute
        twitter: https://twitter.com/akinikolaidis
      - name: Katie Bottenhorn
        role: Secretary
        image: katie_bottenhorn
        affiliation: Florida International University, Department of Psychology
        twitter: https://twitter.com/62442katieb
      - name: Tristan Glatard
        role: Treasurer
        image: tristan_glatard
        affiliation: Concordia University, Department of Computer Science and Software Engineering
        twitter: https://twitter.com/TristanGlatard

        # elect chair, secretary, treasurer
      - name: Janine Bijsterbosch
        role: Chair Elect
        image: janine_bijsterbosch
        affiliation: Washington University in St Louis, Department of Radiology (Medical School)
        twitter: https://twitter.com/PersonomicsLab
      - name: Johanna Bayer
        role: Secretary Elect
        image: johanna_bayer
        affiliation: The University of Melbourne, Faculty for Medicine, Dentistry and Health Sciences
        twitter: https://twitter.com/likeajumprope
      - name: Benjamin De Leener
        role: Treasurer Elect
        image: benjamin_de_leener
        affiliation: Polytechnique Montreal, Department of Computer Engineering and Software Engineering
        twitter: https://twitter.com/bendeleener

        # hackathon
      - name: Tibor Auer
        role: Hackathon co-chair
        image: tibor_auer
        affiliation: Univeristy of Surrey, School of Psychology
        twitter: https://twitter.com/TiborAuer
      - name: Matteo Mancini
        role: Hackathon co-chair
        image: matteo_mancini
        affiliation: University of Sussex, Department of Neuroscience, Brighton and Sussex Medical School
        twitter: https://www.twitter.com/ingmatman

        # OSR
      - name: Eva Alonso Ortiz
        role: Open Science Room Co-Chair
        image: eva_alonso_ortiz
        affiliation: Polytechnique Montreal, Department of Electrical Engineering
        twitter: https://twitter.com/EvaAlonsoOrtiz
      - name: Gabriel Gonzalez-Escamilla
        role: Open Science Room Co-Chair
        image: gabriel_gonzalez_escamilla
        affiliation: University Medical Center of the Johannes Gutember University Mainz
        twitter: https://twitter.com/NeuroGabriel
        
        # Volunteer Coordinator
      - name: Sofie Valk
        role: Volunteer Coordinator
        image: sofie_valk
        affiliation: Max Planck for Human Cognitive and Brain Sciences; FZ Jülich 
        twitter: https://twitter.com/sofievalk
      
      - name: Melvin Selim Atay
        role: Inclusivity Officer
        image: melvin_selim_atay
        affiliation: Middle East Technical University, Department of Neuroscience and Neurotechnology 
        twitter: https://twitter.com/i_am_mel_dev

        # past chair, secretary, treasurer
      - name: Camille Maumet
        role: Past Chair
        image: camille_maumet
        affiliation: Inria, Univ Rennes, CNRS, Inserm
        twitter: https://twitter.com/cmaumet
      - name: Ana Van Gulick
        role: Past Secretary
        image: ana_van_gulick
        affiliation: Figshare; Carnegie Mellon University, University Libraries and Department of Psychology
        twitter: https://twitter.com/anavangulick
      - name: Eugene Duff
        role: Past Treasurer
        image: eugene_duff
        affiliation: University of Oxford, Department of Pediatrics
        twitter: https://twitter.com/EugenePDuff

        # liaison
      - name: Pierre Bellec
        role: Council Liaison
        image: pierre_bellec
        affiliation: University of Montreal, CRIUGM, Montreal, Canada
        twitter: https://twitter.com/pierre_bellec

  sponsors:
    title: Our sponsors
    subtitle: We are grateful for the generous support of our 2020 sponsors
    titleopp: Sponsorship opportunities
    tiersimage: /images/illustrations/ossig_sponsorship_tiers.jpg
    subtitleopp: Interested in supporting us? Please see our sponsorship opportunities below!
    sponsors:
      - name: Open science champions
        oursponsors:
          - name: "Openneuro"
            image: /images/logos/openneuro_logo.png
            url: https://openneuro.org/
      - name: Hackathon champions
        oursponsors:
          - name: "INCF"
            image: /images/logos/incf_logo.png
            url: https://www.incf.org/
          - name: "Courtois NeuroMod"
            image: /images/logos/cneuromod_logo.svg
            url: https://www.cneuromod.ca/
            height: 5em
          - name: "CONP"
            image: /images/logos/conp_logo.png
            url: https://conp.ca/
      - name: Hackathon supporters
        oursponsors:
          - name: "WIN"
            image: /images/logos/logo_WIN_clear.png
            url: https://www.win.ox.ac.uk/
          - name: "UNIQUE"
            image: /images/logos/Unique_logo.png
            url: http://unique.quebec
          - name: "Quebec Bio-Imaging Network"
            image: /images/logos/QBIN_logo.png
            url: https://www.rbiq-qbin.qc.ca/Accueil
      - name: Sponsors
        oursponsors:
          - name: "OHBM Australian chapter"
            image: "/images/logos/OHBM_australian_chapter.png"
            url: "https://ohbmaustralia.wordpress.com/"

  section2:
    title: Open science is an umbrella.
    subtitle: We're here to help grow the community supporting it.
    id: openumbrella
    features:
      - title: Open data
        text: Sharing neuroimaging data isn't easy, but we can make it easier. We're interested in understanding how OHBM members share data, where they encounter difficulties, and what kinds of new infrastruce and ethics can make next-generation data-sharing possible.
        # Icon (from /images/illustrations/icons/___.svg)
        icon: mouse-globe
      - title: Open code
        text: Analysis code is often a second-class citizen in neuroimaging research, but we can change that. We help to teach scientists best-practices in software development—and how those practices can result in real-world gains in research quality and output.
        icon: laptop-cloud
      - title: Open publishing
        text: Papers shouldn't hide behind paywalls. We want to help create solutions to enable new, open-acess platforms and to facilitate free information.
        icon: doc-sync


  footer:
    # Logo (from /images/logos/___)
    logo: ossig_logo.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
      - link: https://github.com/OHBM
        # Icons are from Font Awesome
        icon: github
      - link: https://twitter.com/ohbmopen
        icon: twitter
    bulmalogo: false
